apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 275058537329.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 275058537329.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 776e07aa
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
